### ISSUE TITLE
libticables slv_bulk_read timeout

### ISSUE THREAD

**Issue by ghost** [debrouxl/tilibs#2] opened 2014-06-18 18:42 UTC
Sort of getting desperate here.

I've tried to get tilp to work on OSX, Win and Linux today, and still haven't succeeded. The ultimate goal is to install KnightOS.
On OSX and on Linux I managed to get tilp to connect to the calculator (TI 84+, boot code 1.02; OS 2.55MP), but as soon as I try to dump the ROM (both via double click on operating system and via Tools->dump Rom), I get a slv_bulk_read (Operation timed out) error.
Any ideas?

This has happened on OSX Mavericks, and ArchLinux, with tilp 1.16 and 1.17 and the newest libticables from the AUR.

**Comment by diabl0w** [comment] 2024-03-12 07:17
I know this is old but I am suffering from the same or very similar bug. However, **I know exactly what is happening**, I just don't know **how** its happening.

First, I am on Linux, using a Silverlink Cable, with a TI 83+ calc.

Second, I can confirm it is an issue with the "v2" versions of the tilibs. If I use your new `tilp` but disable the version checks, and use the previous versions of the tilibs (every lib is 1 version lower), everything works fine. 

The issue is not triggered by getting a DirList, and not by transferring small files. **The issue is specifically trying to transfer larger files to the calculator**.

**Here is where it gets interesting**:
```
ticalcs-INFO: 02:30:27.838:  PC->TI: RTS (size=0x1932=6450, id=06, name=CHESS, attr=0)
ticalcs-INFO: 02:30:27.856:  TI->PC: ACK
ticalcs-INFO: 02:30:27.885:  TI->PC: CTS
ticalcs-INFO: 02:30:27.885:  PC->TI: ACK
ticalcs-INFO: 02:30:27.886:  PC->TI: XDP (0x0032 = 50 bytes)

(tilp:91531): ticables-WARNING **: 02:30:32.891: slv_bulk_read (Operation timed out).
```
Here you can see that the transfer stopped after `50 bytes`. In the old working version, the part that says `50 bytes` will instead `6450 bytes`, matching up to the full file size that is noted a few lines above it. Did you notice something interesting about the hex representation of those bytes? Yes, they are the same except the transferred version has `0x00` at the big end. This is further confirmed by trying to transfer a different file:
```
ticalcs-INFO: 03:13:12.558:  PC->TI: RTS (size=0x041E=1054, id=06, name=DOCDE7, attr=0)
ticalcs-INFO: 03:13:12.580:  TI->PC: ACK
ticalcs-INFO: 03:13:12.596:  TI->PC: CTS
ticalcs-INFO: 03:13:12.596:  PC->TI: ACK
ticalcs-INFO: 03:13:12.636:  PC->TI: XDP (0x001E = 30 bytes)

(tilp:129505): ticables-WARNING **: 03:13:17.640: slv_bulk_read (Operation timed out).
```
The `0x1E` is preserved, but the `0x04` was dropped

**Comment by diabl0w** [comment] 2024-03-12 09:32
I guess technically unrelated to original issue because I found the problem which is [this](https://github.com/debrouxl/tilibs/commit/57733d551c73ad31c76723ae68ec5957051113a2#diff-d0963c4038481f47dde30a438ccb60ad7686c4657a4cc2762ee6f25d2e5db644) commit.

Reverting it resolved the issue

**Comment by adriweb** [comment] 2024-03-12 09:34
Yes it's my fault in this commit, the `length` parameter needs to be a `uint16_t` for the `ti*_send_XDP` functions.
Easy enough to fix.

**Comment by diabl0w** [comment] 2024-03-12 09:36
> Yes it's my fault in this commit, the `length` parameter needs to be a `uint16_t` for the `ti*_send_XDP` functions. Easy enough to fix.

I ended up finding that too, but when i made the adjustment to uint16_t, it didn't seem to fix the issue. but it could *definitely* be just because I am struggling to get clean builds. I'll try to test again

**Comment by debrouxl** [comment] 2024-03-12 09:36
Thanks for the report, diabl0w. Adriweb and I discussed this elsewhere this morning, but neither of us followed up here before you came to the same conclusion as me.

**Comment by diabl0w** [comment] 2024-03-12 09:56
okay i can confirm changing *all* of the `tiXX_send_XDP unint8_t length` to `uint16_t` does work. Im still a bit confused, because I originally just changed the ti**82**_send_XDP to uint16_t length, but that didn't work. Maybe the TI83+ uses the TI73 call? not sure. just to scratch my curiosity, i'd appreciate if either of you were able to explain why changing the ti82 only didn't work

**Comment by debrouxl** [comment] 2024-03-12 09:59
Right, the 83+ code uses `ti73_send_XDP()`.

**Comment by adriweb** [comment] 2024-03-12 10:20
There were a few other mistakes, https://github.com/adriweb/tilibs/commit/83246f6182ab565104688455b86a86503df940bd should fix them.
I'll let @debrouxl review that and integrate it, I guess.

**Comment by debrouxl** [comment] 2024-03-13 17:47
First part integrated yesterday, with an additional fix.

**Comment by diabl0w** [comment] 2024-03-13 18:09
> First part integrated yesterday, with an additional fix.

Thanks, im really surprised the compiler doesnt catch this. I am not a super experienced programmer, but I do have some programming history and typically it wouldnt even let me compile doing something like this. If i wanted to do it on purpose for some reason, i would have to cast it just to compile succesfully.

Off topic, but id appreciate the help: What is the preferred method of compiling this with tilp? Specifically for the gtk3 branch. Ive been using a modified version of the bundled `.sh` script but it seems a bit hacky. I have 0 understanding of cmake so i tried to use it but failed pretty quickly.

**Comment by adriweb** [comment] 2024-03-13 18:14
Regarding the build with cmake, you can see how the CI does it in the
GitHub actions workflow. It should be pretty straightforward, and even
requires less deps than with the autotools.

**Comment by diabl0w** [comment] 2024-03-13 18:27
> Regarding the build with cmake, you can see how the CI does it in the GitHub actions workflow. It should be pretty straightforward, and even requires less deps than with the autotools.

oh wow thats a huge help. ive been meaning to look into what all this github action/workflow stuff was... thank you.

Also, looking into some c documentation, i may have been wrong about the compiler. i think C may be happy to convert int16 into int8 and just overflow it without warnings. not too sure tho

**Comment by debrouxl** [comment] 2024-03-16 16:44
Adriweb mentioned that the original reporter's account was deleted, which I missed. Closing the issue as it's unlikely that we'll get a reply.

**Closed by debrouxl** 2024-03-16 16:44 UTC
